name: gitartwork from a contribution graph
on: 
  push:
  pull_request:
  schedule:
    - cron: '* */24 * * *'
  workflow_dispatch:  
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Siam-CSE/gitartwork@v1
        with:
           user_name: Siam-CSE
           text: SIAM
      - uses: Siam-CSE/simple-push-action@v1
